/*GENERATED FILE, DO NOT MODIFY MANUALLY!*/
/*GENERATED BY "PoolNamesGenerator"*/

namespace Pooling
{
    public static class DemoPoolConfigNames
    {
        public const string FooCube = "FooCube";
        public const string BarSphere = "BarSphere";
    }
}
